// Generated by generate_wrap_init.pl -- DO NOT MODIFY!

#define GLIBMM_INCLUDED_FROM_WRAP_INIT_CC
#include <glibmm.h>
#include <gskmm/wrap_init.h>
#include <glibmm/error.h>
#include <glibmm/object.h>

// #include the widget headers so that we can call the get_type() static methods:
#include "enums.h"
#include "roundedrect.h"
#include "transform.h"

#if defined(__GNUC__) || defined (__clang__)
// gcc or clang, https://gitlab.gnome.org/GNOME/glibmm/-/issues/119
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpragmas"
#pragma GCC diagnostic ignored "-Winconsistent-dllimport"
#elif defined(_MSC_VER)
#pragma warning( push )
#pragma warning( disable : 4273 ) // Disable MSVC warning C4273 in wrap_init.cc momentarily
#endif

extern "C"
{
//Declarations of the *_get_type() functions:


//Declarations of the *_error_quark() functions:

} // extern "C"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#elif defined(_MSC_VER)
#pragma warning( pop )
#endif

namespace Gsk {

//Declarations of the *_Class::wrap_new() methods, instead of including all the private headers:


void wrap_init()
{
  // Register Error domains in the main namespace:

  // Map gtypes to gtkmm wrapper-creation functions:

  // Register the gtkmm gtypes:

} // wrap_init()

} // Gsk

