// Generated by gmmproc 2.84.0 -- DO NOT MODIFY!


#include <glibmm.h>

#include <gtkmm/fixedlayout.h>
#include <gtkmm/private/fixedlayout_p.h>


/* Copyright (C) 2025 The gtkmm Development Team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>

namespace
{
} // anonymous namespace


namespace Glib
{

Glib::RefPtr<Gtk::FixedLayout> wrap(GtkFixedLayout* object, bool take_copy)
{
  return Glib::make_refptr_for_instance<Gtk::FixedLayout>( dynamic_cast<Gtk::FixedLayout*> (Glib::wrap_auto ((GObject*)(object), take_copy)) );
  //We use dynamic_cast<> in case of multiple inheritance.
}

} /* namespace Glib */


namespace Gtk
{


/* The *_Class implementation: */

const Glib::Class& FixedLayout_Class::init()
{
  if(!gtype_) // create the GType if necessary
  {
    // Do not derive a GType, or use a derived class:
    gtype_ = gtk_fixed_layout_get_type();

  }

  return *this;
}


Glib::ObjectBase* FixedLayout_Class::wrap_new(GObject* object)
{
  return new FixedLayout((GtkFixedLayout*)object);
}


/* The implementation: */

GtkFixedLayout* FixedLayout::gobj_copy()
{
  reference();
  return gobj();
}

FixedLayout::FixedLayout(const Glib::ConstructParams& construct_params)
:
  LayoutManager(construct_params)
{

}

FixedLayout::FixedLayout(GtkFixedLayout* castitem)
:
  LayoutManager((GtkLayoutManager*)(castitem))
{}


FixedLayout::FixedLayout(FixedLayout&& src) noexcept
: LayoutManager(std::move(src))
{}

FixedLayout& FixedLayout::operator=(FixedLayout&& src) noexcept
{
  LayoutManager::operator=(std::move(src));
  return *this;
}


FixedLayout::~FixedLayout() noexcept
{}


FixedLayout::CppClassType FixedLayout::fixedlayout_class_; // initialize static member

GType FixedLayout::get_type()
{
  return fixedlayout_class_.init().get_type();
}


GType FixedLayout::get_base_type()
{
  return gtk_fixed_layout_get_type();
}


FixedLayout::FixedLayout()
:
  // Mark this class as non-derived to allow C++ vfuncs to be skipped.
  Glib::ObjectBase(nullptr),
  LayoutManager(Glib::ConstructParams(fixedlayout_class_.init()))
{
  

}

Glib::RefPtr<FixedLayout> FixedLayout::create()
{
  return Glib::make_refptr_for_instance<FixedLayout>( new FixedLayout() );
}


} // namespace Gtk


