// Generated by gmmproc 2.84.0 -- DO NOT MODIFY!


#include <glibmm.h>

#include <gtkmm/fixedlayoutchild.h>
#include <gtkmm/private/fixedlayoutchild_p.h>


/* Copyright (C) 2025 The gtkmm Development Team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>

namespace
{
} // anonymous namespace


namespace Glib
{

Glib::RefPtr<Gtk::FixedLayoutChild> wrap(GtkFixedLayoutChild* object, bool take_copy)
{
  return Glib::make_refptr_for_instance<Gtk::FixedLayoutChild>( dynamic_cast<Gtk::FixedLayoutChild*> (Glib::wrap_auto ((GObject*)(object), take_copy)) );
  //We use dynamic_cast<> in case of multiple inheritance.
}

} /* namespace Glib */


namespace Gtk
{


/* The *_Class implementation: */

const Glib::Class& FixedLayoutChild_Class::init()
{
  if(!gtype_) // create the GType if necessary
  {
    // Do not derive a GType, or use a derived class:
    gtype_ = gtk_fixed_layout_child_get_type();

  }

  return *this;
}


Glib::ObjectBase* FixedLayoutChild_Class::wrap_new(GObject* object)
{
  return new FixedLayoutChild((GtkFixedLayoutChild*)object);
}


/* The implementation: */

GtkFixedLayoutChild* FixedLayoutChild::gobj_copy()
{
  reference();
  return gobj();
}

FixedLayoutChild::FixedLayoutChild(const Glib::ConstructParams& construct_params)
:
  LayoutChild(construct_params)
{

}

FixedLayoutChild::FixedLayoutChild(GtkFixedLayoutChild* castitem)
:
  LayoutChild((GtkLayoutChild*)(castitem))
{}


FixedLayoutChild::FixedLayoutChild(FixedLayoutChild&& src) noexcept
: LayoutChild(std::move(src))
{}

FixedLayoutChild& FixedLayoutChild::operator=(FixedLayoutChild&& src) noexcept
{
  LayoutChild::operator=(std::move(src));
  return *this;
}


FixedLayoutChild::~FixedLayoutChild() noexcept
{}


FixedLayoutChild::CppClassType FixedLayoutChild::fixedlayoutchild_class_; // initialize static member

GType FixedLayoutChild::get_type()
{
  return fixedlayoutchild_class_.init().get_type();
}


GType FixedLayoutChild::get_base_type()
{
  return gtk_fixed_layout_child_get_type();
}


FixedLayoutChild::FixedLayoutChild()
:
  // Mark this class as non-derived to allow C++ vfuncs to be skipped.
  Glib::ObjectBase(nullptr),
  LayoutChild(Glib::ConstructParams(fixedlayoutchild_class_.init()))
{
  

}

void FixedLayoutChild::set_transform(const Glib::RefPtr<const Gsk::Transform>& transform)
{
  gtk_fixed_layout_child_set_transform(gobj(), const_cast<GskTransform*>(Glib::unwrap(transform)));
}

Glib::RefPtr<Gsk::Transform> FixedLayoutChild::get_transform() const
{
  auto retvalue = Glib::wrap(gtk_fixed_layout_child_get_transform(const_cast<GtkFixedLayoutChild*>(gobj())));
  if(retvalue)
    retvalue->reference(); //The function does not do a ref for us.
  return retvalue;
}


static_assert(Glib::Traits::ValueCompatibleWithWrapProperty<Glib::RefPtr<Gsk::Transform>>::value,
  "Type Glib::RefPtr<Gsk::Transform> cannot be used in _WRAP_PROPERTY. "
  "There is no suitable template specialization of Glib::Value<>.");

Glib::PropertyProxy< Glib::RefPtr<Gsk::Transform> > FixedLayoutChild::property_transform() 
{
  return Glib::PropertyProxy< Glib::RefPtr<Gsk::Transform> >(this, "transform");
}

Glib::PropertyProxy_ReadOnly< Glib::RefPtr<Gsk::Transform> > FixedLayoutChild::property_transform() const
{
  return Glib::PropertyProxy_ReadOnly< Glib::RefPtr<Gsk::Transform> >(this, "transform");
}


} // namespace Gtk


